/* GENERATED by src/sms/mktiles.py from src/msdos/charset.h. Do not edit.
 * Glyph codes are what the shadow screen holds; a tile number is the
 * glyph itself unless a T_ variant below says otherwise. */
#ifndef TILES_H
#define TILES_H

#define UDG_CARD_TL              0x80
#define UDG_CARD_BL              0x81
#define UDG_CARD_TOP             0x82
#define UDG_CARD_BOT             0x83
#define UDG_CARD_TOP_TRIM        0x84
#define UDG_CARD_BOT_TRIM        0x85
#define UDG_CARD_VERT            0x86
#define UDG_CARD_BR_STUB         0x96
#define UDG_CARD_TR_STUB         0x97
#define UDG_BACK_RCOL_TOP        0x9B
#define UDG_BACK_RCOL_MID        0x9C
#define UDG_BACK_RCOL_BOT        0x9D
#define UDG_BACK_L_TOP           0x9E
#define UDG_BACK_R_TOP           0x9F
#define UDG_BACK_L_MID           0xA0
#define UDG_BACK_R_MID           0xA1
#define UDG_BACK_L_BOT           0xA2
#define UDG_BACK_R_BOT           0xA3
#define UDG_BOX_TL               0xA4
#define UDG_BOX_TR               0xA5
#define UDG_BOX_H                0xA6
#define UDG_BOX_BL               0xA7
#define UDG_BOX_BR               0xA8
#define UDG_BOX_V                0xA9
#define UDG_RANK_2               0xAA
#define UDG_RANK_3               0xAB
#define UDG_RANK_4               0xAC
#define UDG_RANK_5               0xAD
#define UDG_RANK_6               0xAE
#define UDG_RANK_7               0xAF
#define UDG_RANK_8               0xB0
#define UDG_RANK_9               0xB1
#define UDG_RANK_T               0xB2
#define UDG_RANK_J               0xB3
#define UDG_RANK_Q               0xB4
#define UDG_RANK_K               0xB5
#define UDG_RANK_A               0xB6
#define UDG_SUIT_SPADE           0xB7
#define UDG_SUIT_CLUB            0xB8
#define UDG_SUIT_DIAMOND         0xB9
#define UDG_SUIT_HEART           0xBA
#define UDG_CHIP                 0xBC
#define UDG_SCREEN_TL            0xC1
#define UDG_SCREEN_TR            0xC2
#define UDG_SCREEN_BL            0xC3
#define UDG_SCREEN_BR            0xC4

#define T_CARD_VERT_FACE         0x186  /* left border on the card face */
#define T_RANK_RED               0x1AA  /* 13 ranks 2..A in red */
#define T_BLANK_FACE             0x1BB  /* card face interior */
#define T_TOPBAR                 0x100  /* + glyph: space and card tops, barred */
#define T_HILITE                 0x140  /* + glyph - 0x20: ASCII 0x20-0x5F, black on gold */

/* Palette indices; see mktiles.py. */
#define PAL_PAPER  0
#define PAL_WHITE  1
#define PAL_RED    2
#define PAL_BLACK  3
#define PAL_FACE   4
#define PAL_FELT   5
#define PAL_GOLD   6
#define PAL_COUNT  7

extern const unsigned char sms_tileset[];
extern const unsigned char sms_palette[];

#endif /* TILES_H */
