#!/usr/bin/env bash
# build.sh -- assemble the RCA Studio II 5 Card Stud client with Macroassembler AS.
#
#   ./build.sh                                   build/5card.st2
#   ENDPOINT=http://192.168.1.10:8080/ ./build.sh  another server
#
# Everything lands in build/. The checker and the ST2 packer come from the
# cartridge bring-up in the firmware tree (pico/studio2/tools): checkrom.py
# refuses a 3-cycle opcode or RF used as anything but an LDN pointer, and
# mkst2.py refuses code on a page an app may not claim.
#
# Env:
#   ENDPOINT=...       server (default https://5card.carr-designs.com/)
#   FUJI_FIRMWARE=...  firmware tree (default ~/Workspace/fujinet-firmware)
#   ASL=...            the assembler (default ~/asl/asl, else asl on PATH)
set -euo pipefail
cd "$(dirname "$0")"

FUJI_FIRMWARE="${FUJI_FIRMWARE:-$HOME/Workspace/fujinet-firmware}"
TOOLS="$FUJI_FIRMWARE/pico/studio2/tools"
[ -f "$TOOLS/mkst2.py" ] || { echo "build.sh: no $TOOLS/mkst2.py (set FUJI_FIRMWARE)" >&2; exit 1; }

ASL=${ASL:-$HOME/asl/asl}
[ -x "$ASL" ] || ASL=$(command -v asl) || { echo "build.sh: no asl (Macroassembler AS)" >&2; exit 1; }

mkdir -p build

# Regenerated every run so a stale server cannot survive an environment change.
# The devicespec carries its own N: unless the endpoint already names a unit.
ENDPOINT="${ENDPOINT:-https://5card.carr-designs.com/}"
case "$ENDPOINT" in
    N:*|N[1-8]:*) SPEC="$ENDPOINT" ;;
    *)            SPEC="N:$ENDPOINT" ;;
esac
cat > build/endpoint.inc <<EOC
; GENERATED by build.sh -- do not edit.
UENDPT: DB      "$SPEC", 0
EOC

(cd src && "$ASL" -q -U -L -i . -i ../build -o ../build/5card.p \
    -olist ../build/5card.lst 5card.asm)
python3 "$TOOLS/checkrom.py" build/5card.lst
python3 "$TOOLS/mkst2.py" build/5card.p build/5card.st2 5CARD
