/* GENERATED by src/atari7800/mkchr.py from src/coleco/font.bin and udg.h.
 * Tile numbers in mt_tiles; $20-$5F are ASCII. 128 of 128 tiles used.
 * Do not edit. */
#ifndef TILES_H
#define TILES_H

#define T_CARD_TL_RG           0x01
#define T_CARD_BL_RG           0x02
#define T_CARD_TOP_RG          0x03
#define T_CARD_BOT_RG          0x04
#define T_CARD_TOP_TRIM_RG     0x05
#define T_CARD_BOT_TRIM_RG     0x06
#define T_CARD_VERT_RG         0x07
#define T_CARD_BR_STUB_RG      0x08
#define T_CARD_TR_STUB_RG      0x09
#define T_BOX_TL_RG            0x0A
#define T_BOX_TR_RG            0x0B
#define T_BOX_H_RG             0x0C
#define T_BOX_BL_RG            0x0D
#define T_BOX_BR_RG            0x0E
#define T_BOX_V_RG             0x0F
#define T_CHIP_RG              0x10
#define T_CARD_VERT_RW         0x11
#define T_BACK_RCOL_TOP_RW     0x12
#define T_BACK_RCOL_MID_RW     0x13
#define T_BACK_RCOL_BOT_RW     0x14
#define T_BACK_L_TOP_RW        0x15
#define T_BACK_R_TOP_RW        0x16
#define T_BACK_L_MID_RW        0x17
#define T_BACK_R_MID_RW        0x18
#define T_BACK_L_BOT_RW        0x19
#define T_BACK_R_BOT_RW        0x1A
#define T_BLANK_W              0x1B  /* card face interior */
#define T_SCREEN_TL_GK         0x1C
#define T_SCREEN_TR_GK         0x1D
#define T_SCREEN_BL_GK         0x1E
#define T_SCREEN_BR_GK         0x1F
#define T_RANK_RW              0x60  /* 13 ranks 2..A, red on white */
#define T_RANK_KW              0x6D  /* 13 ranks 2..A, black on white */
#define T_SUIT_DIAMOND_RW      0x7A
#define T_SUIT_HEART_RW        0x7B
#define T_SUIT_SPADE_KW        0x7C
#define T_SUIT_CLUB_KW         0x7D
#define T_HIDDEN_L_RW          0x7E
#define T_HIDDEN_R_RW          0x7F

#endif /* TILES_H */
