#!/usr/bin/env python3
"""Emit src/cardart.inc: everything a card face is made of.

Every stamp here is 5 wide and 5 tall so ONE blitter (DSTAMP in fujidisp.inc)
draws all of it, and a 10-pixel card face is exactly two stamps: a rank then a
pip. One byte per row, bit 7 = leftmost pixel, stored pre-shifted -- DSTAMP
tests bit 7 and shifts left, so right-aligned bits would cost two shifts per
row for nothing.

The ranks are the font's own uppercase glyphs (imported, not retyped) moved
into the middle of a 5-wide field here rather than at +1 at runtime. That is
what lets the ten be an ordinary table entry instead of a special case, and it
means the wire's lowercase 't' never reaches the font -- whose lowercase forms
are squashed four-row variants, right for a typed name and wrong for a rank.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mkfont import GLYPHS

W = H = 5

# The ten is the one rank the 3x5 font cannot spell: "T" is poker shorthand,
# not a number. Five wide is exactly enough for a 1px "1" and a 3px "0".
TEN = ["#.###", "#.#.#", "#.#.#", "#.#.#", "#.###"]

# 5x5 is the floor for telling four suits apart. Heart and diamond differ in
# the top row and the bottom half. Spade and club are the hard pair, so they
# are separated at SILHOUETTE level rather than by one interior pixel: the
# spade widens downward to a solid row and necks into a 1px stem, the club
# narrows downward from a notched shoulder. Both draw blue, so a mis-read
# costs tidiness only.
PIPS = [
    ("h", "hearts",   [".#.#.", "#####", "#####", ".###.", "..#.."], "CVAL2"),
    ("d", "diamonds", ["..#..", ".###.", "#####", ".###.", "..#.."], "CVAL2"),
    ("s", "spades",   ["..#..", ".###.", "#####", "..#..", ".###."], "CVAL1"),
    ("c", "clubs",    ["..#..", "##.##", ".###.", "..#..", ".###."], "CVAL1"),
    (None, "anything else -- the catch-all",
     [".....", ".....", ".....", ".....", "....."], "CVAL1"),
]

# The wire sends ranks lowercase: 23456789tjqka. The table is keyed on those
# bytes as they arrive, so nothing is case-folded at runtime.
RANKS = list("23456789tjqka")


def rank_art(ch):
    if ch == "t":
        return TEN
    # A 3-wide font row sits in bits 2..0; bit 2 is the leftmost pixel. Moving
    # it to bits 6..4 centres the glyph in the 5-wide field.
    return [("." + "".join("#" if GLYPHS[ch.upper()].split(";")[r][i] == "#"
                           else "." for i in range(3)) + ".")
            for r in range(H)]


def lattice():
    """The face-down card: one diagonal lattice across the whole 10x5 face,
    cut into two 5-wide halves. Period 3, so it reads as a weave rather than
    as ink -- a 50% checkerboard at this size is just a red block."""
    rows = ["".join("#" if (x + y) % 3 == 0 else "." for x in range(2 * W))
            for y in range(H)]
    return [r[:W] for r in rows], [r[W:] for r in rows]


def pack(row):
    if len(row) != W:
        sys.exit("mkcards: row %r is not %d wide" % (row, W))
    bits = 0
    for i, c in enumerate(row):           # leftmost pixel -> bit 7
        if c == "#":
            bits |= 1 << (7 - i)
    return bits


def block(out, art, label):
    if len(art) != H:
        sys.exit("mkcards: %s is not %d tall" % (label, H))
    for row in art:
        out.append("\tDB %03XH\t\t; %s  %s" % (pack(row), row.replace(".", " "),
                                              label))
        label = ""


def main():
    out = [
        "; GENERATED by tools/mkcards.py -- do not edit by hand.",
        "; 5x5 stamps, one byte per row, bit 7 = leftmost pixel, stored",
        "; pre-shifted: DSTAMP tests bit 7 and shifts left.",
        ";",
        "; The two tables below are walked with a signed ADC, so no offset may",
        "; reach 128 -- same trap as font.inc. CRANKS tops out at 65 of 127,",
        "; which is one more rank table away from wrapping silently.",
    ]

    out += ["", "; ---- rank art, 5 wide, %d entries ----" % (len(RANKS) + 1),
            "CRANKS:"]
    for ch in RANKS:
        block(out, rank_art(ch), "'%s'" % ch)
    block(out, ["....."] * H, "blank -- the catch-all")

    out += ["", "; ---- suit pips, 5 wide, %d entries ----" % len(PIPS),
            "CPIPS:"]
    for _, what, art, _ in PIPS:
        block(out, art, what)

    left, right = lattice()
    out += ["", "; ---- the face-down card, one lattice in two halves ----",
            "CBAKL:"]
    block(out, left, "left half")
    out += ["", "CBAKR:"]
    block(out, right, "right half")

    out += ["", "; ---- key -> art. The last row's key is 0, which matches",
            "; ---- anything, so a corrupt byte lands on the blank.",
            "RNKTB:\t\t\t; DB key, offset into CRANKS"]
    for i, ch in enumerate(RANKS):
        out.append("\tDB '%s',%d" % (ch, i * H))
    out.append("\tDB 0,%d" % (len(RANKS) * H))

    out += ["", "SUITTB:\t\t\t; DB key, offset into CPIPS, colour"]
    for i, (key, what, _, col) in enumerate(PIPS):
        out.append("\tDB %s,%d,%s\t\t; %s"
                   % ("'%s'" % key if key else "0", i * H, col, what))
    out.append("")

    path = sys.argv[1] if len(sys.argv) > 1 else "src/cardart.inc"
    open(path, "w").write("\n".join(out) + "\n")
    n = (len(RANKS) + 1 + len(PIPS) + 2) * H + (len(RANKS) + 1) * 2 + len(PIPS) * 3
    print("%s: %d stamps, %d bytes of art and tables"
          % (path, len(RANKS) + 1 + len(PIPS) + 2, n))


main()
